const ROUNDS = [
  [
    { id:"r1p1", username:"nasa", avatar:"🚀", location:"Kennedy Space Center", imagePlaceholder:"🌌", likes:2481392, caption:"Earth from 400 miles up. Our astronauts aboard the ISS captured this view of the Pacific Ocean.", timestamp:"3 hours ago", isFake:false, fakeClue:"" },
    { id:"r1p2", username:"natgeo", avatar:"🦁", location:"Serengeti, Tanzania", imagePlaceholder:"🦁", likes:1204830, caption:"A lion family at dusk. The Serengeti remains one of the last places this scene plays out daily.", timestamp:"5 hours ago", isFake:false, fakeClue:"" },
    { id:"r1p3", username:"n4sa_official", avatar:"🚀", location:"Washington D.C.", imagePlaceholder:"🌍", likes:847, caption:"NASA has announced FREE tickets to watch a rocket launch!! Click the link in our bio before they run out!!!", timestamp:"1 hour ago", isFake:true, fakeClue:"Username uses '4' instead of 'a' — a classic impersonation trick. NASA never gives away free launch tickets via Instagram. The urgency language and only 847 likes are major red flags." },
    { id:"r1p4", username:"whitehouse", avatar:"🏛️", location:"Washington, D.C.", imagePlaceholder:"🏛️", likes:487291, caption:"The President today signed the new infrastructure bill into law — the largest investment in American roads and bridges in decades.", timestamp:"6 hours ago", isFake:false, fakeClue:"" },
    { id:"r1p5", username:"nike", avatar:"👟", location:"Beaverton, Oregon", imagePlaceholder:"✔️", likes:892041, caption:"Just do it. New Air Max — dropping this Friday. Link in bio.", timestamp:"4 hours ago", isFake:false, fakeClue:"" }
  ],
  [
    { id:"r2p1", username:"who", avatar:"🏥", location:"Geneva, Switzerland", imagePlaceholder:"🩺", likes:391042, caption:"Hand hygiene remains one of the most effective ways to prevent the spread of infections. Wash hands for at least 20 seconds.", timestamp:"2 hours ago", isFake:false, fakeClue:"" },
    { id:"r2p2", username:"worldhealthorg", avatar:"🏥", location:"Geneva", imagePlaceholder:"💊", likes:3201, caption:"BREAKING: WHO confirms that drinking hot lemon water every morning CURES all viral infections. Share before they delete this!!", timestamp:"45 minutes ago", isFake:true, fakeClue:"WHO would never make an unscientific cure claim. 'Share before they delete this' is conspiracy-bait. Real WHO posts cite sources and have millions of likes, not 3,000." },
    { id:"r2p3", username:"nytimes", avatar:"📰", location:"New York, NY", imagePlaceholder:"🗞️", likes:214830, caption:"The Federal Reserve held interest rates steady today, citing ongoing uncertainty in global markets.", timestamp:"1 hour ago", isFake:false, fakeClue:"" },
    { id:"r2p4", username:"apple", avatar:"🍎", location:"Cupertino, CA", imagePlaceholder:"📱", likes:1032840, caption:"Shot on iPhone. Every detail, every moment. #ShotOniPhone", timestamp:"8 hours ago", isFake:false, fakeClue:"" },
    { id:"r2p5", username:"natgeo", avatar:"🌿", location:"Amazon Basin, Brazil", imagePlaceholder:"🌿", likes:988320, caption:"The Amazon rainforest is home to 10% of all species on Earth. Protecting it matters.", timestamp:"3 hours ago", isFake:false, fakeClue:"" }
  ],
  [
    { id:"r3p1", username:"espn", avatar:"🏀", location:"Bristol, CT", imagePlaceholder:"🏀", likes:703912, caption:"What a finish. Buzzer beater to send it to overtime. Full highlights on ESPN+ now.", timestamp:"2 hours ago", isFake:false, fakeClue:"" },
    { id:"r3p2", username:"tesla", avatar:"⚡", location:"Austin, TX", imagePlaceholder:"🚗", likes:1120400, caption:"Model 3. Designed for the road ahead. Order yours today.", timestamp:"5 hours ago", isFake:false, fakeClue:"" },
    { id:"r3p3", username:"google", avatar:"🔍", location:"Mountain View, CA", imagePlaceholder:"🔍", likes:882041, caption:"Search smarter. Try the new AI-powered search features available now.", timestamp:"4 hours ago", isFake:false, fakeClue:"" },
    { id:"r3p4", username:"n1ke_giveaway_official", avatar:"👟", location:"Nike HQ", imagePlaceholder:"🎁", likes:214, caption:"HUGE GIVEAWAY! Nike is giving away 500 pairs of shoes! Follow us, like this post, and tag 3 friends. Winners announced tomorrow!", timestamp:"30 minutes ago", isFake:true, fakeClue:"Username swaps 'i' for '1'. Real Nike giveaways would have millions of likes, not 214. The follow + like + tag formula is the most common fake giveaway tactic on social media." },
    { id:"r3p5", username:"nps_gov", avatar:"🏕️", location:"Yellowstone National Park", imagePlaceholder:"🏔️", likes:329810, caption:"Old Faithful erupted 17 times today. Plan your visit at nps.gov. #Yellowstone", timestamp:"6 hours ago", isFake:false, fakeClue:"" }
  ]
];
